"""initial migration

Revision ID: 586131216f6
Revises: None
Create Date: 2015-07-26 16:30:52.969275

"""

# revision identifiers, used by Alembic.
revision = '586131216f6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
